---
language: "python"
python: "2.7"

env:
  - SITE_AND_INVENTORY="tests/main.yml -i tests/inventory"

before_install:
  - "apt-get install systemd libpam-systemd systemd-ui"

install:
  - "pip install ansible==2.1"
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - "ansible-playbook $SITE_AND_INVENTORY --syntax-check"
  - "ansible-playbook $SITE_AND_INVENTORY --connection=local -vvvv"
  - >
    ansible-playbook $SITE_AND_INVENTORY --connection=local
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - >
    sudo iptables -L
    | grep -q '--dport 22'
    && (echo 'SSH is open test: pass' && exit 0)
    || (echo 'SSH is open test: fail' && exit 1)
  - >
    sudo iptables -L
    | grep -q '--dport 80'
    && (echo 'HTTP is open test: pass' && exit 0)
    || (echo 'HTTP is open test: fail' && exit 1)
  - >
    sudo iptables -L
    | grep -q '--dport 443'
    && (echo 'HTTPS is open test: pass' && exit 0)
    || (echo 'HTTPS is open test: fail' && exit 1)
